
version: 1.0.0-win-{build}
image: Visual Studio 2019 Preview
configuration: Release
platform: x64
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  CppCompilerAndLinker: clang
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip
  NUGET_PACKAGES: 'C:\projects\fata-morgana\packages'
cache:
  - 'packages'
before_build:
- pwsh: >-
    Invoke-WebRequest "https://download.visualstudio.microsoft.com/download/pr/41e4c58f-3ac9-43f6-84b6-f57d2135331a/3691b61f15f1f5f844d687e542c4dc72/dotnet-sdk-3.0.100-preview7-012821-win-x64.zip" -OutFile "dotnet-sdk-3.0.100-preview7-012821-win-x64.zip"
    Expand-Archive "dotnet-sdk-3.0.100-preview7-012821-win-x64.zip" -DestinationPath "dotnet"
    Set-Item Env:Path "C:\projects\fata-morgana\dotnet;$Env:Path"
build_script:
- pwsh: .\dotnet\dotnet.exe publish -c Release -r win-x64 -o dist --version-suffix "win-$APPVEYOR_BUILD_NUMBER"
artifacts:
- path: 'dist\'
